DELTA_THRESHOLD = 3.0
DELTA_DISJOINT = 1.0
DELTA_WEIGHT = 0.3

MUTATE_CONNECTIONS_CHANCE = 0.25
PERTURB_CHANCE = 0.9
LINK_MUTATION_CHANCE = 2.0
NODE_MUTATION_CHANCE = 0.5
BIAS_MUTATION_CHANCE = 0.4
DISABLE_MUTATION_CHANCE = 0.4
ENABLE_MUTATION_CHANCE = 0.2
STEP_MUTATION = 0.1
MAX_NODES = 1000000
MAX_STALENESS = 15
CROSSOVER_CHANCE = 0.75

INPUT_SIZE = 5
OUTPUT_SIZE = 1
